export const SCROBBLER_STORAGE_KEY = 'SCROBBLER_STORAGE_KEY';

export const SCROBBLER__UPDATE = 'SCROBBLER__UPDATE';
export const SCROBBLER__UPDATE_ENABLED = 'SCROBBLER__UPDATE_ENABLED';
export const SCROBBLER__START = 'SCROBBLER__START';
export const SCROBBLER__STOP = 'SCROBBLER__STOP';
export const SCROBBLER__NEW = 'SCROBBLER__NEW';
export const SCROBBLER__AUTH_PROCESSING = 'SCROBBLER__AUTH_PROCESSING';
export const SCROBBLER__SUCCESS = 'SCROBBLER__SUCCESS';
