export const PRESETS_STORAGE_KEY = 'PRESETS_STORAGE_KEY';

export const PRESETS__UPDATE = 'PRESETS__UPDATE';
export const PRESETS__ADD_PRESET = 'PRESETS__ADD_PRESET';
export const PRESETS__UPDATE_PRESET = 'PRESETS__UPDATE_PRESET';
export const PRESETS__UPDATE_PRESETS = 'PRESETS__UPDATE_PRESETS';
export const PRESETS__DELETE_PRESET = 'PRESETS__DELETE_PRESET';
export const PRESETS__UPDATE_CURRENT = 'PRESETS__UPDATE_CURRENT';
export const PRESETS__UPDATE_AUTO = 'PRESETS__UPDATE_AUTO';
