export const EQUALIZER_STORAGE_KEY = 'EQUALIZER_STORAGE_KEY';

export const EQUALIZER__UPDATE_BIQUAD_FILTERS = 'EQUALIZER__UPDATE_BIQUAD_FILTERS';
export const EQUALIZER__UPDATE_EFFECT_NAME = 'EQUALIZER__UPDATE_EFFECT_NAME';
export const EQUALIZER__UPDATE_EFFECT_GAIN = 'EQUALIZER__UPDATE_EFFECT_GAIN';
export const EQUALIZER__UPDATE_SURROUND = 'EQUALIZER__UPDATE_SURROUND';
export const EQUALIZER__UPDATE = 'EQUALIZER__UPDATE';


