export const PAUSE = 'PAUSE';
export const PLAYING = 'PLAYING';
export const TIMEUPDATE = 'TIMEUPDATE';

export const LOAD_EQUALIZER = 'LOAD_EQUALIZER';
export const UPDATE_BIQUAD_FILTERS = 'UPDATE_BIQUAD_FILTERS';

export const LOAD_PRESETS = 'LOAD_PRESETS';
export const ADD_PRESET = 'ADD_PRESET';
export const DELETE_PRESET = 'DELETE_PRESET';
export const UPDATE_PRESET = 'UPDATE_PRESET';
export const UPDATE_PRESETS = 'UPDATE_PRESETS';
export const UPDATE_CURRENT_PRESET = 'UPDATE_CURRENT_PRESET';
export const UPDATE_AUTO_PRESET = 'UPDATE_AUTO_PRESET';

export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';

export const LOAD_VIEW = 'LOAD_VIEW';
export const UPDATE_VIEW = 'UPDATE_VIEW';
export const UPDATE_BLOCKS_ORDER = 'UPDATE_BLOCKS_ORDER';
export const UPDATE_PLAYER_DISPLAY = 'UPDATE_PLAYER_DISPLAY';
export const UPDATE_PLAYLISTS = 'UPDATE_PLAYLISTS';

export const LOAD_SCROBBLER = 'LOAD_SCROBBLER';
export const SWITCH_SCROBBLER = 'SWITCH_SCROBBLER';

